language: elixir
elixir:
- 1.4
otp_release:
- 19.0
sudo: false
addons:
  postgresql: '9.4'
before_script:
- psql -c 'create database peepchat_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: MA/B8uswhyAcrApHsy04QH4hp34nYqg7mTlze43YkRjZrVF6F2d3qnlciNLbLmeOBU+i5nTzzKxVLeDV9VI678sZtvoFQVwOep+WI4yJtd5L9nu7INC127ruixc3mHXd+SKlLAOwidXX8fCT8JDPKgq3MDc9PB3gFyYxPo9Uf6yABeKrPcRjqBVl8QYt09HIjwiBothayVWohr30hVUbFXXN5+NBj9P+UpIMeRWogpgTr4kqrEXQRcAC7dP/VpJJ1PPTyyLxh2RyOlX4xE58Kbcvj4A+rmgnEB9TbfVA31O74JuGKq7cglQTejSkbS0cOuxzWW3zJp9/sBAU4IdXelNhAlFr4B+YDyeNpZrqkI4oLCA8/KqxDLwqUTHH96jyRnLsn7P/UwrOA0k++k2zIhjEbYACo0MXNiI3c6nFbpvYEfqs4Slcu6fvQWmYGNgEX2mWTwiBECsmF2Y4WbBocwBSDySGkaQM2BLeExS48jLQkaiLd8nikD1KUhazY/M186nIG0SVMiDxP4OoKKjXwVyqzN5shCtq+o4EhZfJxZc8RI6RJ5T33iffNaJihJfKGRFOoLcEwB4FvMziJ0v8B4Oe2fk/TwmnCnzfjPup45yEql+AHUz+kC02NtgzJMYtdRTGRJaZV7JwBVAOdqXFzyrERdUkFoABvKlEnAm2Zwk=
  app: frozen-coast-87972
  on:
    repo: mike-north/peepchat-api
